#plot3 (assumes - plot1.R has been run before to create the data table pwr2)
plot(pwr2$timestamp,pwr2$Sub_metering_1, type="l", col="black", xlab="",ylab="Energy sub metering")
lines(pwr2$timestamp,pwr2$Sub_metering_2, type="l", col="red")
lines(pwr2$timestamp,pwr2$Sub_metering_3, type="l", col="blue")
legend(x="topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1), lwd=c(1,1),col=c("black","red","blue"),cex=0.75)
dev.copy(png,"plot3.png",width=480,height=480)
dev.off()
