#plot#4 (assumes - plot1.R has been run before to create the data table pwr2)
par(mfrow=c(2,2))
plot(pwr2$timestamp,pwr2$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(pwr2$timestamp,pwr2$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(pwr2$timestamp,pwr2$Sub_metering_1, type="l", col="black", xlab="",ylab="Energy sub metering")
lines(pwr2$timestamp,pwr2$Sub_metering_2, type="l", col="red")
lines(pwr2$timestamp,pwr2$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n", lty=c(1,1),col=c("black","red","blue"),cex=1)
plot(pwr2$timestamp,pwr2$Global_reactive_power, type="l", xlab="datetime",ylab="Global_reactive_power")
dev.copy(png,"plot4.png",width=480,height=480)
dev.off()
